export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAIL = "REQUEST_FAIL";
export const REQUEST_TO_BE_LOADED = "REQUEST_TO_BE_LOADED";
export const REMOVE_REQUEST = "REMOVE_REQUEST";
export const REQUEST_LOADED = "REQUEST_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REQUEST_DELETED = "REQUEST_DELETED";
